Update This_workflow_never_end.yaml

diff --git a/.github/workflows/This_workflow_never_end.yaml b/.github/workflows/This_workflow_never_end.yaml
--- a/.github/workflows/This_workflow_never_end.yaml
+++ b/.github/workflows/This_workflow_never_end.yaml
@@ -19,7 +19,7 @@ jobs:
 
 
       - name: Run long Python script
-        run: python long_script.py || echo "Python script exited with error"
+        run: python -u long_script.py || echo "Python script exited with error"
 
       - name: Start new workflow if timeout is near
         if: always()
